version: "3"
services:
    nodeserver:
        build:
            context: ./
        ports:
            - "3000:3000"
    nginx:
        restart: always
        build:
            context: ./
        ports:
            - "80:80"